### ISSUE TITLE
BleManagerStopScan should be invoked on stopScan()

### ISSUE THREAD

**Issue by rnevius** [innoveit/react-native-ble-manager#395]
### Version

- react-native-ble-manager v6.5.0
- react-native v0.56.0
- Android v9

### Expected behaviour

The `BleManagerStopScan` event should be invoked when `stopScan()` is called.

### Actual behaviour

`BleManagerStopScan` is only called when a scan finishes automatically (i.e. after `seconds` have elapsed since calling `scan()`) or when the scan fails.

### Steps to reproduce

Call `BleManager.stopScan()`. No event is triggered.

**Comment by smdjeff** [comment]
was it fixed?

**Comment by MD3XTER** [comment]
I still have this issue

**Comment by rnevius** [comment]
A fix for a (related?) iOS bug was [committed](https://github.com/innoveit/react-native-ble-manager/commit/837ee9249dd3ee85f0937b9adb25ca07dc2fe4c6) a couple of days ago, but I don't believe this issue is resolved on Android @marcosinigaglia

**Comment by marcosinigaglia** [comment]
Yes, Is fixed only on iOS, my fault.

**Comment by marcosinigaglia** [comment]
Try the new release.

**Comment by MD3XTER** [comment]
> Try the new release.

Is this issue fixed for iOS in this release? `v6.6.4`

**Comment by marcosinigaglia** [comment]
In iOS is fixed in v6.6.5.

**Comment by MD3XTER** [comment]
But, it's not released yet, right?

**Comment by MD3XTER** [comment]
> In iOS is fixed in v6.6.5.

I updated the library and `BleManagerStopScan` is still not triggered. @marcosinigaglia did it work on your end?

p.s I don't think I need to relink dependencies, but just in case, do I need to do something else after updating the library from npm?

**Comment by marcosinigaglia** [comment]
@MD3XTER do you still have the problem?

**Comment by MD3XTER** [comment]
Yes, latest version, didn’t fix it for me

**Comment by marcosinigaglia** [comment]
Can you debug the library code on xcode? Are you sure that you update the library?

**Comment by MD3XTER** [comment]
I will check if the latest changes in your release are present in node_modules as well. I will debug in xcode. Should I just watch the log?

**Comment by marcosinigaglia** [comment]
Check if you arrive in this line https://github.com/innoveit/react-native-ble-manager/blob/c6189ecf9f81905f750039d22e36691974a2993e/ios/BleManager.m#L357

**Comment by MD3XTER** [comment]
@marcosinigaglia I tested now the code and it seems like it works. I must have missed something. I think it's safe to close this issue, thank you for the fix :)
